"use client";

import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Skeleton,
  Spinner,
  Table,
  TableBody,
  TableCell,
  TableColumn,
  TableHeader,
  TableRow,
} from "@nextui-org/react";
import { AcademicStatusEntry } from "autogestion-frvm/types";
import axios from "axios";
import { useEffect, useState } from "react";
import HistoricCourses from "../HistoricCourses";
import AcademicStatusYearEntry from "./AcademicStatusYearEntry";

export default function AcademicStatusPanel() {
  const academic: Array<AcademicStatusEntry> = [
    {
      nombreMateria: "Metodologías Agiles (Elec.)",
      codigoMateria: "885",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Metodologías Agiles (Elec.)\nNo aprobó ni está inscripto a Diseño de Sistemas",
      faltaReg: "No regularizó Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Metodologías Agiles (Elec.)",
        codigoAcademico: "885",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Sistemas Operativos",
      codigoMateria: "230",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 8 (4 hs.) Tomo: 268 Folio: 30",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Sistemas Operativos",
        codigoAcademico: "230",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Desarrollo de Aplicaciones Web (Elec.)",
      codigoMateria: "578",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Desarrollo de Aplicaciones Web (Elec.)\nNo aprobó ni está inscripto a Programación Avanzada(Elec.)",
      faltaReg: "No regularizó Programación Avanzada(Elec.)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Desarrollo de Aplicaciones Web (Elec.)",
        codigoAcademico: "578",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Física II",
      codigoMateria: "226",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 9 (5 hs.) Tomo: 267 Folio: 53",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Física II",
        codigoAcademico: "226",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Diseño de Arquitecturas de Software(Elec",
      codigoMateria: "809",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Diseño de Arquitecturas de Software(Elec.)\nNo aprobó ni está inscripto a Diseño de Sistemas",
      faltaReg: "No regularizó Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Diseño de Arquitecturas de Software(Elec",
        codigoAcademico: "809",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Seguridad Informática(Elec.)",
      codigoMateria: "650",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Seguridad Informática(Elec.)\nNo aprobó ni está inscripto a Redes de Información",
      faltaReg: "No regularizó Redes de Información",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Seguridad Informática(Elec.)",
        codigoAcademico: "650",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Metodologías Ágiles en el Desarrollo de",
      codigoMateria: "791",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Metodologías Ágiles en el Desarrollo de Software(Elec.)\nNo aprobó ni está inscripto a Diseño de Sistemas",
      faltaReg: "No regularizó Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Metodologías Ágiles en el Desarrollo de",
        codigoAcademico: "791",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Tecnología de Redes Avanzadas (Elec.)",
      codigoMateria: "579",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Tecnología de Redes Avanzadas (Elec.)\nNo aprobó ni está inscripto a Redes de Información",
      faltaReg: "No regularizó Redes de Información",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Tecnología de Redes Avanzadas (Elec.)",
        codigoAcademico: "579",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Tecnologías DLT/Blockchain y Contratos I",
      codigoMateria: "967",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Tecnologías DLT/Blockchain y Contratos Inteligentes (Elec.)\nNo aprobó ni está inscripto a Redes de Información",
      faltaReg: "No regularizó Redes de Información",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Tecnologías DLT/Blockchain y Contratos I",
        codigoAcademico: "967",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Sistemas de Gestión",
      codigoMateria: "541",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Sistemas de Gestión\nNo aprobó ni está inscripto a Administración de Recursos (Ord. 1150)\nNo aprobó ni está inscripto a Investigación Operativa (Ord. 1150)\nNo aprobó ni está inscripto a Simulación (Ord. 1150)",
      faltaReg:
        "No regularizó Administración de Recursos (Ord. 1150)\nNo regularizó Investigación Operativa (Ord. 1150)\nNo regularizó Simulación (Ord. 1150)\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Sistemas de Gestión",
        codigoAcademico: "541",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Comunicaciones",
      codigoMateria: "332",
      nivel: "3",
      plan: "2008",
      estado: "Ap. Directa en 2023 (1C)",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Comunicaciones",
        codigoAcademico: "332",
      },
      estadoMateria: "REGULARIZADA",
    },
    {
      nombreMateria: "Economía",
      codigoMateria: "308",
      nivel: "3",
      plan: "2008",
      estado: "Aprobada con 9 (3 hs.) Tomo: 283 Folio: 197",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Economía",
        codigoAcademico: "308",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Investigación Operativa",
      codigoMateria: "437",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Investigación Operativa\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)",
      faltaReg: "No regularizó Probabilidades y Estadísticas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Investigación Operativa",
        codigoAcademico: "437",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Inteligencia Artificial",
      codigoMateria: "543",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Inteligencia Artificial\nNo aprobó ni está inscripto a Investigación Operativa (Ord. 1150)\nNo aprobó ni está inscripto a Simulación (Ord. 1150)",
      faltaReg:
        "No regularizó Investigación Operativa (Ord. 1150)\nNo regularizó Simulación (Ord. 1150)\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Inteligencia Artificial",
        codigoAcademico: "543",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Comunicaciones y Redes",
      codigoMateria: "330",
      nivel: "2",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Comunicaciones y Redes",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Comunicaciones y Redes",
        codigoAcademico: "330",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Testing de Software(Elec.)",
      codigoMateria: "803",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Testing de Software(Elec.)\nNo aprobó ni está inscripto a Ingeniería de Software",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Testing de Software(Elec.)",
        codigoAcademico: "803",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Ingeniería y Sociedad",
      codigoMateria: "110",
      nivel: "3",
      plan: "2008",
      estado: "Aprobada con 8 (2 hs.) Tomo: 277 Folio: 162",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Ingeniería y Sociedad",
        codigoAcademico: "110",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Reingeniería de Procesos de Negocios (El",
      codigoMateria: "392",
      nivel: "3",
      plan: "2008",
      estado: "Aprobada con 10 (2 hs.) Tomo: 278 Folio: 58",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "10",
      totalFaltas: 0,
      materia: {
        nombre: "Reingeniería de Procesos de Negocios (El",
        codigoAcademico: "392",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Matemática Discreta",
      codigoMateria: "121",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 8 (3 hs.) Tomo: 260 Folio: 184",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Matemática Discreta",
        codigoAcademico: "121",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Álgebra y Geometría Analítica",
      codigoMateria: "101",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 9 (5 hs.) Tomo: 252 Folio: 133",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Álgebra y Geometría Analítica",
        codigoAcademico: "101",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Inglés II",
      codigoMateria: "212",
      nivel: "3",
      plan: "2008",
      estado: "Aprobada con 9 (2 hs.) Tomo: 272 Folio: 182",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Inglés II",
        codigoAcademico: "212",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Sistemas de Soporte a las Decisiones(Ele",
      codigoMateria: "629",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Sistemas de Soporte a las Decisiones(Elec.)\nNo aprobó ni está inscripto a Diseño de Sistemas\nNo aprobó ni está inscripto a Probabilidades y Estadísticas",
      faltaReg: "No regularizó Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Sistemas de Soporte a las Decisiones(Ele",
        codigoAcademico: "629",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Administración Gerencial",
      codigoMateria: "542",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Administración Gerencial\nNo aprobó ni está inscripto a Administración de Recursos (Ord. 1150)\nNo aprobó ni está inscripto a Investigación Operativa (Ord. 1150)",
      faltaReg:
        "No regularizó Administración de Recursos (Ord. 1150)\nNo regularizó Investigación Operativa (Ord. 1150)\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Administración Gerencial",
        codigoAcademico: "542",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Teoría de Control",
      codigoMateria: "440",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Teoría de Control\nNo aprobó ni está inscripto a Química (Ord. 1150)",
      faltaReg: "No regularizó Química (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Teoría de Control",
        codigoAcademico: "440",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Inglés I",
      codigoMateria: "111",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 9 (2 hs.) Tomo: 254 Folio: 154",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Inglés I",
        codigoAcademico: "111",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Paradigmas de Programación",
      codigoMateria: "229",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 10 (4 hs.) Tomo: 268 Folio: 188",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "10",
      totalFaltas: 0,
      materia: {
        nombre: "Paradigmas de Programación",
        codigoAcademico: "229",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Diseño Arquitectónico(Elec.)",
      codigoMateria: "630",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Diseño Arquitectónico(Elec.)\nNo aprobó ni está inscripto a Diseño de Sistemas",
      faltaReg: "No regularizó Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Diseño Arquitectónico(Elec.)",
        codigoAcademico: "630",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Diseño de Procesos de Negocios(Elec.)",
      codigoMateria: "556",
      nivel: "3",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Diseño de Procesos de Negocios(Elec.)\nNo aprobó ni está inscripto a Ingeniería de Software",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Diseño de Procesos de Negocios(Elec.)",
        codigoAcademico: "556",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Gestión de Proyectos Informáticos(Elec.)",
      codigoMateria: "633",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Gestión de Proyectos Informáticos(Elec.)\nNo aprobó ni está inscripto a Administración de Recursos\nNo aprobó ni está inscripto a Redes de Información\nNo aprobó ni está inscripto a Teoría de Control",
      faltaReg:
        "No regularizó Administración de Recursos\nNo regularizó Redes de Información\nNo regularizó Teoría de Control\nNo aprobó ni está inscripto a Probabilidades y Estadísticas\nNo aprobó ni está inscripto a Diseño de Sistemas\nNo aprobó ni está inscripto a Química",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Gestión de Proyectos Informáticos(Elec.)",
        codigoAcademico: "633",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Ingeniería del Conocimiento(Elec.)",
      codigoMateria: "557",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Ingeniería del Conocimiento(Elec.)\nNo aprobó ni está inscripto a Inteligencia Artificial",
      faltaReg: "No regularizó Inteligencia Artificial",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Ingeniería del Conocimiento(Elec.)",
        codigoAcademico: "557",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Arquitectura de Computadoras",
      codigoMateria: "123",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 9 (4 hs.) Tomo: 258 Folio: 55",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Arquitectura de Computadoras",
        codigoAcademico: "123",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Análisis Matemático II",
      codigoMateria: "203",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 10 (5 hs.) Tomo: 262 Folio: 197",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "10",
      totalFaltas: 0,
      materia: {
        nombre: "Análisis Matemático II",
        codigoAcademico: "203",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Gestión de Datos",
      codigoMateria: "333",
      nivel: "3",
      plan: "2008",
      estado: "Aprobada con 10 (4 hs.) Tomo: 283 Folio: 127",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "10",
      totalFaltas: 0,
      materia: {
        nombre: "Gestión de Datos",
        codigoAcademico: "333",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Calidad en Desarrollo de Sistemas(Elec.)",
      codigoMateria: "632",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Calidad en Desarrollo de Sistemas(Elec.)\nNo aprobó ni está inscripto a Administración de Recursos\nNo aprobó ni está inscripto a Teoría de Control\nNo aprobó ni está inscripto a Redes de Información\nNo aprobó ni está inscripto a Investigación Operativa",
      faltaReg:
        "No regularizó Administración de Recursos\nNo regularizó Ingeniería de Software\nNo aprobó ni está inscripto a Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Calidad en Desarrollo de Sistemas(Elec.)",
        codigoAcademico: "632",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Redes de Información",
      codigoMateria: "334",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Redes de Información\nNo aprobó ni está inscripto a Comunicaciones (Ord. 1150)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Redes de Información",
        codigoAcademico: "334",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Práctica Supervisada",
      codigoMateria: "519",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Redes de Información (Ord. 973)\nNo regularizó Administración de Recursos (Ord. 973)\nNo regularizó Ingeniería de Software (Ord. 973)\nNo regularizó Legislación (Ord. 973)\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 973)\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 973)\nNo aprobó ni está inscripto a Comunicaciones (Ord. 973)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Práctica Supervisada",
        codigoAcademico: "519",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Bases de Datos Avanzadas (Elec.)",
      codigoMateria: "527",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Bases de Datos Avanzadas (Elec.)\nNo aprobó ni está inscripto a Sistemas de Soporte a las Decisiones(Elec.)",
      faltaReg: "No regularizó Sistemas de Soporte a las Decisiones(Elec.)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Bases de Datos Avanzadas (Elec.)",
        codigoAcademico: "527",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Lenguajes de Descripción de Hardware(Ele",
      codigoMateria: "552",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Lenguajes de Descripción de Hardware(Elec.)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Lenguajes de Descripción de Hardware(Ele",
        codigoAcademico: "552",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Proyecto Final",
      codigoMateria: "550",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Proyecto Final\nNo aprobó ni está inscripto a Redes de Información (Ord. 1150)\nNo aprobó ni está inscripto a Ingeniería de Software (Ord. 1150)\nNo aprobó ni está inscripto a Teoría de Control (Ord. 1150)\nNo aprobó ni está inscripto a Legislación (Ord. 1150)\nNo aprobó ni está inscripto a Inteligencia Artificial (Ord. 1150)\nNo aprobó ni está inscripto a Administración Gerencial (Ord. 1150)\nNo aprobó ni está inscripto a Sistemas de Gestión (Ord. 1150)\nLe faltan aprobar 20 de 22 horas anuales del conjunto Electivas 3er.año ó Electivas 4to.año ó Electivas 5to.año ó Electivas 2do.año\nCódigo materia=Horas (x ninguna)\n392=2,556=x,683=x,801=x,802=x,966=x,397=x,629=x\n791=x,809=x,885=x,527=x,555=x,557=x,578=x,579=x\n631=x,636=x,650=x,789=x,792=x,803=x,854=x,890=x\n (Ord. 1150)\nNo aprobó ni está inscripto a Práctica Supervisada (Ord. 1150)",
      faltaReg:
        "No regularizó Redes de Información (Ord. 1150)\nNo regularizó Administración de Recursos (Ord. 1150)\nNo regularizó Ingeniería de Software (Ord. 1150)\nNo regularizó Legislación (Ord. 1150)\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 1150)\nNo aprobó ni está inscripto a Comunicaciones (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Proyecto Final",
        codigoAcademico: "550",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Probabilidades y Estadísticas",
      codigoMateria: "204",
      nivel: "3",
      plan: "2008",
      estado: "Cursa en 3K1 Aula 301 Central",
      faltaAprobar: "No regularizó Probabilidades y Estadísticas",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Probabilidades y Estadísticas",
        codigoAcademico: "204",
      },
      estadoMateria: "CURSANDO",
    },
    {
      nombreMateria: "Comunicaciones Inalámbricas(Elec.)",
      codigoMateria: "555",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Comunicaciones Inalámbricas(Elec.)\nNo aprobó ni está inscripto a Redes de Información",
      faltaReg: "No regularizó Redes de Información",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Comunicaciones Inalámbricas(Elec.)",
        codigoAcademico: "555",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Auditoría de Sistemas(Elec.)",
      codigoMateria: "631",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Auditoría de Sistemas(Elec.)\nNo aprobó ni está inscripto a Redes de Información\nNo aprobó ni está inscripto a Administración de Recursos",
      faltaReg: "No regularizó Ingeniería de Software",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Auditoría de Sistemas(Elec.)",
        codigoAcademico: "631",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Habilitación Profesional",
      codigoMateria: "450",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Habilitación Profesional\nNo aprobó al menos 8 materias de 1er año (Ord. 1150)",
      faltaReg:
        "No regularizó Diseño de Sistemas (Ord. 1150)\nNo regularizó Comunicaciones y Redes (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Habilitación Profesional",
        codigoAcademico: "450",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Diseño Electrónico con Dispositivos de H",
      codigoMateria: "551",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Diseño Electrónico con Dispositivos de Hardware Programable(Elec.)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Diseño Electrónico con Dispositivos de H",
        codigoAcademico: "551",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Taller de Programación I (Elec.)",
      codigoMateria: "801",
      nivel: "3",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Taller de Programación I (Elec.)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Taller de Programación I (Elec.)",
        codigoAcademico: "801",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Administración de Recursos",
      codigoMateria: "436",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Administración de Recursos\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 1150)",
      faltaReg: "No regularizó Diseño de Sistemas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Administración de Recursos",
        codigoAcademico: "436",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Sistemas de Representación",
      codigoMateria: "115",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 9 (3 hs.) Tomo: 268 Folio: 200",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Sistemas de Representación",
        codigoAcademico: "115",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Seguridad en Redes(Elec.)",
      codigoMateria: "635",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Seguridad en Redes(Elec.)\nNo aprobó ni está inscripto a Redes de Información",
      faltaReg:
        "No regularizó Redes de Información\nNo aprobó ni está inscripto a Comunicaciones",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Seguridad en Redes(Elec.)",
        codigoAcademico: "635",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Legislación",
      codigoMateria: "409",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Legislación",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Legislación",
        codigoAcademico: "409",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Taller de Programación II (Elec.)",
      codigoMateria: "802",
      nivel: "3",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Taller de Programación II (Elec.)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Taller de Programación II (Elec.)",
        codigoAcademico: "802",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Análisis de Sistemas",
      codigoMateria: "227",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 8 (6 hs.) Tomo: 278 Folio: 55",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Análisis de Sistemas",
        codigoAcademico: "227",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Sintaxis y Semántica de los Lenguajes",
      codigoMateria: "228",
      nivel: "2",
      plan: "2008",
      estado: "Aprobada con 8 (4 hs.) Tomo: 268 Folio: 186",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Sintaxis y Semántica de los Lenguajes",
        codigoAcademico: "228",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Calidad en el Desarrollo de Software(Ele",
      codigoMateria: "789",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Calidad en el Desarrollo de Software(Elec.)",
      faltaReg:
        "No regularizó Ingeniería de Software\nNo regularizó Programación Avanzada(Elec.)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Calidad en el Desarrollo de Software(Ele",
        codigoAcademico: "789",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Informática Industrial(Elec.)",
      codigoMateria: "634",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Informática Industrial(Elec.)\nNo aprobó ni está inscripto a Administración de Recursos\nNo aprobó ni está inscripto a Teoría de Control",
      faltaReg:
        "No regularizó Administración de Recursos\nNo regularizó Teoría de Control\nNo aprobó ni está inscripto a Administración y Control de la Producción (Elec.)\nNo aprobó ni está inscripto a Diseño de Sistemas",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Informática Industrial(Elec.)",
        codigoAcademico: "634",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Química",
      codigoMateria: "124",
      nivel: "2",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Química",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Química",
        codigoAcademico: "124",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Sistemas y Organizaciones",
      codigoMateria: "125",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 8 (3 hs.) Tomo: 258 Folio: 6",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Sistemas y Organizaciones",
        codigoAcademico: "125",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Física I",
      codigoMateria: "126",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 6 (5 hs.) Tomo: 257 Folio: 55",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "6",
      totalFaltas: 0,
      materia: {
        nombre: "Física I",
        codigoAcademico: "126",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Algoritmos y Estructuras de Datos",
      codigoMateria: "122",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 8 (5 hs.) Tomo: 258 Folio: 2",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Algoritmos y Estructuras de Datos",
        codigoAcademico: "122",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Diseño de Sistemas",
      codigoMateria: "331",
      nivel: "3",
      plan: "2008",
      estado: "Cursa en 3K2 Aula 408 Central",
      faltaAprobar: "No regularizó Diseño de Sistemas",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Diseño de Sistemas",
        codigoAcademico: "331",
      },
      estadoMateria: "CURSANDO",
    },
    {
      nombreMateria: "Programación Avanzada(Elec.)",
      codigoMateria: "397",
      nivel: "4",
      plan: "2008",
      estado: "Cursa en 4K1 Aula 301 Central",
      faltaAprobar:
        "No regularizó Programación Avanzada(Elec.)\nNo aprobó ni está inscripto a Taller de Programación I (Elec.)\nNo aprobó ni está inscripto a Taller de Programación II (Elec.)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Programación Avanzada(Elec.)",
        codigoAcademico: "397",
      },
      estadoMateria: "CURSANDO",
    },
    {
      nombreMateria: "Taller de Programación (Elec.)",
      codigoMateria: "683",
      nivel: "3",
      plan: "2008",
      estado: "Ap. Directa en 2023 (1C)",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Taller de Programación (Elec.)",
        codigoAcademico: "683",
      },
      estadoMateria: "REGULARIZADA",
    },
    {
      nombreMateria: "Matemática Superior",
      codigoMateria: "336",
      nivel: "3",
      plan: "2008",
      estado: "Aprobada con 9 (4 hs.) Tomo: 274 Folio: 116",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "9",
      totalFaltas: 0,
      materia: {
        nombre: "Matemática Superior",
        codigoAcademico: "336",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Administración y Control de la Producció",
      codigoMateria: "628",
      nivel: "3",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Administración y Control de la Producción (Elec.)",
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Administración y Control de la Producció",
        codigoAcademico: "628",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Gestión y Desarrollo Territorial (Elec.)",
      codigoMateria: "854",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar: "No regularizó Gestión y Desarrollo Territorial (Elec.)",
      faltaReg: "No regularizó al menos 8 materias de 1er año (Ord. 1416)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Gestión y Desarrollo Territorial (Elec.)",
        codigoAcademico: "854",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Simulación",
      codigoMateria: "438",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Simulación\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)",
      faltaReg: "No regularizó Probabilidades y Estadísticas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Simulación",
        codigoAcademico: "438",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Ingeniería de Software",
      codigoMateria: "441",
      nivel: "4",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Ingeniería de Software\nNo aprobó ni está inscripto a Probabilidades y Estadísticas (Ord. 1150)\nNo aprobó ni está inscripto a Diseño de Sistemas (Ord. 1150)",
      faltaReg:
        "No regularizó Probabilidades y Estadísticas (Ord. 1150)\nNo regularizó Diseño de Sistemas (Ord. 1150)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Ingeniería de Software",
        codigoAcademico: "441",
      },
      estadoMateria: "NO_CURSADA",
    },
    {
      nombreMateria: "Análisis Matemático I",
      codigoMateria: "102",
      nivel: "1",
      plan: "2008",
      estado: "Aprobada con 8 (5 hs.) Tomo: 252 Folio: 138",
      faltaAprobar: null,
      faltaReg: null,
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "8",
      totalFaltas: 0,
      materia: {
        nombre: "Análisis Matemático I",
        codigoAcademico: "102",
      },
      estadoMateria: "APROBADA",
    },
    {
      nombreMateria: "Sistemas de Bases de Datos Avanzadas(Ele",
      codigoMateria: "636",
      nivel: "5",
      plan: "2008",
      estado: null,
      faltaAprobar:
        "No regularizó Sistemas de Bases de Datos Avanzadas(Elec.)\nNo aprobó ni está inscripto a Redes de Información\nNo aprobó ni está inscripto a Sistemas de Soporte a las Decisiones(Elec.)",
      faltaReg: "No regularizó Diseño de Arquitecturas de Software(Elec.)",
      anioCursado: null,
      faltasInjustificadas: [],
      faltasJustificadas: [],
      notas: null,
      nota: "",
      totalFaltas: 0,
      materia: {
        nombre: "Sistemas de Bases de Datos Avanzadas(Ele",
        codigoAcademico: "636",
      },
      estadoMateria: "NO_CURSADA",
    },
  ];

  const [loading, isLoading] = useState<boolean>(true);

  /** Holds all academic status data for the student to check. */
  const [academicStatus, setAcademicStatus] = useState<
    Array<AcademicStatusEntry>
  >([]);

  /** An object whose keys represent each career's year. */
  const [academicStatusByYear, setAcademicStatusByYear] = useState<
    Record<string, Array<AcademicStatusEntry>>
  >({});

  useEffect(() => {
    async function fetchAcademicData() {
      isLoading(true);

      try {
        const { data } = await axios<AcademicStatusEntry[]>({
          method: "GET",
          url: "/api/autogestion/courses/academic",
        });

        setAcademicStatus(data);

        isLoading(false);
      } catch (e) {
        console.error(e);
        isLoading(false);
      }
    }

    //if (academicStatus?.length < 1) fetchAcademicData();
    if (academicStatus?.length < 1) {
      // Set raw data.
      setAcademicStatus(academic as any); // test

      // Format data to classify each course by their corresponding year.
      const courseByYear: Record<
        string,
        (Omit<AcademicStatusEntry, "anioCursado"> & { anioCursado: null })[]
      > = {};
      for (const course of academic) {
        if (courseByYear[course.nivel]) courseByYear[course.nivel].push(course);
        else courseByYear[course.nivel] = [course];
      }

      setAcademicStatusByYear(courseByYear);
      isLoading(false);
    }
  });

  return (
    <div className="flex flex-col items-center justify-center mx-4 gap-4">
      <h1 className="my-4 text-xl font-bold">Mi Estado Academico</h1>

      <Card className="w-full flex flex-col items-center justify-center mx-4 px-2 gap-y-2">
        {loading || Object.keys(academicStatusByYear)?.length < 1 ? (
          <div className="flex flex-col items-center justify-center p-4 gap-y-4 text-center">
            <Spinner />
            <h3 className="text-sm font-semibold text-foreground-300">
              Cargando estado academico, esto puede tomar un tiempo...
            </h3>
          </div>
        ) : (
          Object.keys(academicStatusByYear).map((year) => {
            return (
              <AcademicStatusYearEntry
                key={year}
                year={parseInt(year)}
                courses={academicStatusByYear[year]}
              />
            );
          })
        )}
      </Card>
    </div>
  );
}
